=== usnistgov/oar-dmp-schema/model/dmp-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "id": "https://example.com/mids-dmp.schema",
  "title":"NIST MIDAS Data Management Plan record",
  "type":"object",
  "properties" : {
    "title" : {"type" : "string"},
    "startDate": {"type" : "string", 
                  "format":"date"},
    "endDate": {"type" : "string", 
                  "format":"date"},
    "dmpSearchable": {"type" : "string",
                      "enum":["yes", "no"]},
    "funding": {
      "description": "The Funding for the DMP contains funding Funding Number and what is tat number associated with for example Grant Number etc.",
      "type":"object",
      "properties" : {
        
        "grant_source": {"type" : "string",
                         "enum":["Operating Unit", "Division Project Tracking Number", "Grant Number", "Contract Number"]
                        },
        "grant_id": {"type" : "string"}
      }
    },
    "projectDescription": {"type" : "string"},
    "organizations":{
      "type": "array",
      "items": {"$ref": "#/$defs/organization"}
    },
    "primary_NIST_contact": {"$ref": "#/$defs/person"},
    "contributors":{
      "type": "array",
      "items": {"$ref": "#/$defs/contributors"}
    },
    "keyWords":{"type": "array",
                "items":{"type" : "string"}},
    "dataSize":  {"type" : "string",
                  "pattern":"^[0-9]+$"},
    "sizeUnit": {"type" : "string",
                  "enum":["MG", "GB", "TB"]},
    "softwareDevelopment":{
      "type":"object",
      "properties" : {
        "development": {"type" : "string",
                        "enum":["yes", "no"]},
        "softwareUse": {"type" : "string",
                        "enum":["internal", "external", "both"]},
        "softwareDatabase": {"type" : "string",
                        "enum":["yes", "no"]},
        "softwareWebsite": {"type" : "string",
                        "enum":["yes", "no"]}
      }
    },
    "technicalResources":{"type": "array",
                          "items":{"type" : "string"}},
    "ethical_issues": {
      "type":"object",
      "properties" : {
        "ethical_issues_exist": {"type" : "string",
                                "enum":["yes", "no"]},
        "ethical_issues_description": {"type" : "string"},
        "ethical_issues_report": {"type" : "string"},
        "dmp_PII": {"type" : "string",
                    "enum":["yes", "no"]}
      }
    },
    "dataDescription": {"type" : "string"},
    "dataCategories": {"type": "array",
                        "items":{"type" : "string",
                                 "pattern":"^Derived$|^Working$|^Publishable$|^Published Results and SRD$"}           
    },
    "preservationDescription": {"type" : "string"},
    "dataAccess": {"type" : "string"},
    "pathsURLs":{"type": "array",
                          "items":{"type" : "string"}}
  },  
  "$defs":{
    "organization":{
      "type":"object",
      "properties" : {
        "ORG_ID" : {"type" : "number"},
        "name": {"type" : "string"}
      }
    },
    "person":{
      "type":"object",
      "properties" : {
        "firstName" : {"type" : "string"},
        "lastName": {"type" : "string"},
        "orcid": {"type" : "string",
                  "pattern":"^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}$"}
      }
    },
    "contributors": {
      "type":"object",
      "properties" : {
        "contributor": {"$ref": "#/$defs/person"},
        "e_mail": {"type" : "string",
                   "format": "email"},
        "instituion": {"type" : "string"},    
        "role": {"type" : "string"}
      }
    }
  }
}

=== usnistgov/oar-dmp-schema/test-record.json
{
"title": "test",
"startDate": "2023-11-15",
"endDate": "2023-11-15",
"dmpSearchable": "yes",
"funding": {
    "grant_source": "Grant Number",
    "grant_id": "1234"
},
"projectDescription": "Project description example",
"organizations": [
    {
        "ORG_ID": 644,
        "name": "Biosystems and Biomaterials Division"
    },
    {
        "ORG_ID": 647,
        "name": "Applied Chemicals and Materials Division"
    }
],
"primary_NIST_contact": {
    "firstName": "Niksa",
    "lastName": "Blonder",
    "orcid": "1265-1263-4521-7854"
},
"contributors": [
    {
        "contributor": {
            "firstName": "Sam",
            "lastName": "Smith",
            "orcid": "5874-8965-7412-8523"
        },
        "e_mail": "sam@noa.gov",
        "instituion": "NOA",
        "role": "Hosting Institution"
    },
    {
        "contributor": {
            "firstName": "Ray",
            "lastName": "Plante",
            "orcid": "3214-5214-8965-7854"
        },
        "e_mail": "ray@nist.gov",
        "instituion": "NIST",
        "role": "Project Manager"
    }
],
"keyWords": [
    "keyword 2",
    "keyword 1"
],
"dataSize": "35",
"sizeUnit": "GB",
"softwareDevelopment": {
    "development": "yes",
    "softwareUse": "internal",
    "softwareDatabase": "yes",
    "softwareWebsite": "yes"
},
"technicalResources": [
    "resource 2",
    "resource 1"
],
"ethical_issues": {
    "ethical_issues_exist": "yes",
    "ethical_issues_description": "ethical issues example",
    "ethical_issues_report": "report example",
    "dmp_PII": "no"
},
"dataDescription": "generated data example",
"dataCategories": [
    "Derived",
    "Working",
    "Publishable",
    "Published Results and SRD"
]
}
